name: tlhPlugin
version: 0.1.dev
description: tlhPlugin
author: judgetread
authors: [judgetread] 
website: http://thelasthero.net
main: net.thelasthero.tlhPlugin.tlhPlugin

commands:
  spawn:
    description: Send player to spawn
    aliases: [sp]
  shops:
    description: send player to shops world
    aliases: [sh]
  namecolor:
    description: changes a player name color
    aliases: [nc]
  
permissions:
  thelasthero.thief:
    description: blahblah
    default: false
  thelasthero.citizen:
    description: blahblah
    default: false
  thelasthero.protector:
    description: blahblah
    default: false
  thelasthero.doctor:
    description: blahblah
    default: false
  thelasthero.leader:
    description: blahblah
    default: false
  thelasthero.hero:
    description: blahblah
    default: false
  thelasthero.namecolor:
    description: blahblah
    default: false